// Generated from the real backend seed data. Used when VITE_API_URL is not set.
export const mockListings = [
  {
    "id": 20,
    "name": "Canyon View",
    "address": "263 Jackson St, Hayward, CA",
    "lat": 37.65412,
    "lng": -122.06201,
    "rent": 1406,
    "bedrooms": 0,
    "landlord_name": "Eastbay Living",
    "safety_score": 6.1,
    "distance_miles": 0.3,
    "avg_utilities": null,
    "true_cost": 1406,
    "utilities_reported": false,
    "avg_rating": null,
    "review_count": 0
  },
  {
    "id": 10,
    "name": "Grove Villas",
    "address": "258 Foothill Blvd, Hayward, CA",
    "lat": 37.64361,
    "lng": -122.04733,
    "rent": 1295,
    "bedrooms": 0,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 5.5,
    "distance_miles": 1.0,
    "avg_utilities": 142,
    "true_cost": 1437,
    "utilities_reported": true,
    "avg_rating": 4.8,
    "review_count": 4
  },
  {
    "id": 19,
    "name": "Birch Street Studio",
    "address": "1773 Foothill Blvd, Hayward, CA",
    "lat": 37.64239,
    "lng": -122.0591,
    "rent": 1551,
    "bedrooms": 1,
    "landlord_name": "Eastbay Living",
    "safety_score": 7.5,
    "distance_miles": 1.0,
    "avg_utilities": 144,
    "true_cost": 1695,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 3
  },
  {
    "id": 5,
    "name": "Pioneer Court",
    "address": "2205 B St, Hayward, CA",
    "lat": 37.63463,
    "lng": -122.08513,
    "rent": 1586,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 7.8,
    "distance_miles": 2.2,
    "avg_utilities": 126,
    "true_cost": 1712,
    "utilities_reported": true,
    "avg_rating": 2.3,
    "review_count": 3
  },
  {
    "id": 6,
    "name": "Oak Ridge Apartments",
    "address": "1915 Grove Way, Hayward, CA",
    "lat": 37.65058,
    "lng": -122.07277,
    "rent": 1588,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 4.8,
    "distance_miles": 1.0,
    "avg_utilities": 210,
    "true_cost": 1798,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 2
  },
  {
    "id": 12,
    "name": "Summit Suites",
    "address": "1062 D St, Hayward, CA",
    "lat": 37.6548,
    "lng": -122.05505,
    "rent": 1597,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 5.6,
    "distance_miles": 0.2,
    "avg_utilities": 224,
    "true_cost": 1821,
    "utilities_reported": true,
    "avg_rating": 2.5,
    "review_count": 2
  },
  {
    "id": 1,
    "name": "Hillside Commons",
    "address": "1014 Hayward Blvd, Hayward, CA",
    "lat": 37.66037,
    "lng": -122.08545,
    "rent": 1675,
    "bedrooms": 1,
    "landlord_name": "Eastbay Living",
    "safety_score": 5.0,
    "distance_miles": 1.6,
    "avg_utilities": 147,
    "true_cost": 1822,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 6
  },
  {
    "id": 3,
    "name": "Bayview Flats",
    "address": "2187 Foothill Blvd, Hayward, CA",
    "lat": 37.672,
    "lng": -122.06673,
    "rent": 1620,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 8.3,
    "distance_miles": 1.2,
    "avg_utilities": 203,
    "true_cost": 1823,
    "utilities_reported": true,
    "avg_rating": 4.3,
    "review_count": 3
  },
  {
    "id": 18,
    "name": "Skyline Rooms",
    "address": "286 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.6452,
    "lng": -122.0513,
    "rent": 1690,
    "bedrooms": 1,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 6.0,
    "distance_miles": 0.8,
    "avg_utilities": 215,
    "true_cost": 1905,
    "utilities_reported": true,
    "avg_rating": 4.6,
    "review_count": 5
  },
  {
    "id": 9,
    "name": "Harder Place",
    "address": "622 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.66916,
    "lng": -122.05757,
    "rent": 1770,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.3,
    "distance_miles": 0.9,
    "avg_utilities": 212,
    "true_cost": 1982,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 2
  },
  {
    "id": 2,
    "name": "Mission Terrace",
    "address": "2899 D St, Hayward, CA",
    "lat": 37.64826,
    "lng": -122.07622,
    "rent": 1909,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 7.5,
    "distance_miles": 1.2,
    "avg_utilities": 160,
    "true_cost": 2069,
    "utilities_reported": true,
    "avg_rating": 2.3,
    "review_count": 3
  },
  {
    "id": 13,
    "name": "Eden Row",
    "address": "2383 B St, Hayward, CA",
    "lat": 37.66778,
    "lng": -122.0519,
    "rent": 2025,
    "bedrooms": 2,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 6.8,
    "distance_miles": 0.8,
    "avg_utilities": 178,
    "true_cost": 2203,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 6
  },
  {
    "id": 14,
    "name": "Tennyson Gardens",
    "address": "2099 B St, Hayward, CA",
    "lat": 37.65582,
    "lng": -122.04997,
    "rent": 2112,
    "bedrooms": 2,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.7,
    "distance_miles": 0.4,
    "avg_utilities": 182,
    "true_cost": 2294,
    "utilities_reported": true,
    "avg_rating": 2.2,
    "review_count": 4
  },
  {
    "id": 16,
    "name": "Jackson Square Apts",
    "address": "532 Jackson St, Hayward, CA",
    "lat": 37.65437,
    "lng": -122.06964,
    "rent": 2250,
    "bedrooms": 2,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 7.7,
    "distance_miles": 0.7,
    "avg_utilities": 198,
    "true_cost": 2448,
    "utilities_reported": true,
    "avg_rating": 4.7,
    "review_count": 3
  },
  {
    "id": 7,
    "name": "Downtown Lofts",
    "address": "2093 Hayward Blvd, Hayward, CA",
    "lat": 37.66295,
    "lng": -122.05017,
    "rent": 2338,
    "bedrooms": 2,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 6.0,
    "distance_miles": 0.6,
    "avg_utilities": 181,
    "true_cost": 2519,
    "utilities_reported": true,
    "avg_rating": 4.3,
    "review_count": 6
  },
  {
    "id": 4,
    "name": "Carlos Bee Cottage",
    "address": "2272 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.63848,
    "lng": -122.04857,
    "rent": 2398,
    "bedrooms": 2,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 6.1,
    "distance_miles": 1.3,
    "avg_utilities": 190,
    "true_cost": 2588,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 4
  },
  {
    "id": 15,
    "name": "Palisade Place",
    "address": "227 B St, Hayward, CA",
    "lat": 37.64169,
    "lng": -122.08327,
    "rent": 2470,
    "bedrooms": 3,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 8.7,
    "distance_miles": 1.8,
    "avg_utilities": 194,
    "true_cost": 2664,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 3
  },
  {
    "id": 8,
    "name": "Garden Studio",
    "address": "650 Harder Rd, Hayward, CA",
    "lat": 37.66165,
    "lng": -122.05897,
    "rent": 2503,
    "bedrooms": 3,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 8.9,
    "distance_miles": 0.4,
    "avg_utilities": 168,
    "true_cost": 2671,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 3
  },
  {
    "id": 17,
    "name": "Redwood Duplex",
    "address": "2376 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.64692,
    "lng": -122.04268,
    "rent": 2591,
    "bedrooms": 3,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 9.2,
    "distance_miles": 1.0,
    "avg_utilities": 156,
    "true_cost": 2747,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 5
  },
  {
    "id": 11,
    "name": "Foothill House",
    "address": "2846 B St, Hayward, CA",
    "lat": 37.655,
    "lng": -122.04637,
    "rent": 2818,
    "bedrooms": 3,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.7,
    "distance_miles": 0.6,
    "avg_utilities": 220,
    "true_cost": 3038,
    "utilities_reported": true,
    "avg_rating": 4.5,
    "review_count": 4
  }
];

export const mockDetails = {
  "20": {
    "id": 20,
    "name": "Canyon View",
    "address": "263 Jackson St, Hayward, CA",
    "lat": 37.65412,
    "lng": -122.06201,
    "rent": 1406,
    "bedrooms": 0,
    "landlord_name": "Eastbay Living",
    "safety_score": 6.1,
    "distance_miles": 0.3,
    "avg_utilities": null,
    "true_cost": 1406,
    "utilities_reported": false,
    "avg_rating": null,
    "review_count": 0,
    "reviews": [],
    "ai_summary": "No reviews yet. Be the first to share your experience."
  },
  "10": {
    "id": 10,
    "name": "Grove Villas",
    "address": "258 Foothill Blvd, Hayward, CA",
    "lat": 37.64361,
    "lng": -122.04733,
    "rent": 1295,
    "bedrooms": 0,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 5.5,
    "distance_miles": 1.0,
    "avg_utilities": 142,
    "true_cost": 1437,
    "utilities_reported": true,
    "avg_rating": 4.8,
    "review_count": 4,
    "reviews": [
      {
        "id": 34,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 97,
        "text": "Landlord replies within a day and fixed our sink fast. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-08-17T17:08:27.575415",
        "verified": true
      },
      {
        "id": 35,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 178,
        "text": "Management is respectful and gives notice before entering. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-06-22T17:08:27.575451",
        "verified": true
      },
      {
        "id": 33,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 192,
        "text": "Management is respectful and gives notice before entering. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-04-18T17:08:27.575362",
        "verified": true
      },
      {
        "id": 36,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 101,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Rent is fair but the walls are thin.",
        "created_at": "2025-11-15T17:08:27.575480",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 4 student reviews."
  },
  "19": {
    "id": 19,
    "name": "Birch Street Studio",
    "address": "1773 Foothill Blvd, Hayward, CA",
    "lat": 37.64239,
    "lng": -122.0591,
    "rent": 1551,
    "bedrooms": 1,
    "landlord_name": "Eastbay Living",
    "safety_score": 7.5,
    "distance_miles": 1.0,
    "avg_utilities": 144,
    "true_cost": 1695,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 3,
    "reviews": [
      {
        "id": 70,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 108,
        "text": "Mold in the bathroom that was never properly fixed. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-07-25T17:08:27.582277",
        "verified": true
      },
      {
        "id": 69,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 1,
        "safety_rating": 2,
        "monthly_utilities": 157,
        "text": "Landlord kept part of the deposit for normal wear and tear. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-04-27T17:08:27.582234",
        "verified": true
      },
      {
        "id": 71,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 1,
        "safety_rating": 3,
        "monthly_utilities": 167,
        "text": "Hard to reach the landlord, took three weeks to get a response. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-04-17T17:08:27.582306",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 3 student reviews."
  },
  "5": {
    "id": 5,
    "name": "Pioneer Court",
    "address": "2205 B St, Hayward, CA",
    "lat": 37.63463,
    "lng": -122.08513,
    "rent": 1586,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 7.8,
    "distance_miles": 2.2,
    "avg_utilities": 126,
    "true_cost": 1712,
    "utilities_reported": true,
    "avg_rating": 2.3,
    "review_count": 3,
    "reviews": [
      {
        "id": 19,
        "overall_rating": 2,
        "landlord_rating": 1,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 138,
        "text": "Hard to reach the landlord, took three weeks to get a response. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-02-27T17:08:27.571692",
        "verified": true
      },
      {
        "id": 18,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 3,
        "safety_rating": 3,
        "monthly_utilities": 103,
        "text": "Mold in the bathroom that was never properly fixed. Rent is fair but the walls are thin.",
        "created_at": "2025-10-19T17:08:27.571658",
        "verified": true
      },
      {
        "id": 17,
        "overall_rating": 3,
        "landlord_rating": 2,
        "maintenance_rating": 3,
        "safety_rating": 3,
        "monthly_utilities": 138,
        "text": "Mold in the bathroom that was never properly fixed. Rent is fair but the walls are thin.",
        "created_at": "2025-09-16T17:08:27.571605",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 3 student reviews."
  },
  "6": {
    "id": 6,
    "name": "Oak Ridge Apartments",
    "address": "1915 Grove Way, Hayward, CA",
    "lat": 37.65058,
    "lng": -122.07277,
    "rent": 1588,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 4.8,
    "distance_miles": 1.0,
    "avg_utilities": 210,
    "true_cost": 1798,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 2,
    "reviews": [
      {
        "id": 21,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 206,
        "text": "Management is respectful and gives notice before entering. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-08-22T17:08:27.572400",
        "verified": true
      },
      {
        "id": 20,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 213,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-08-05T17:08:27.572346",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 2 student reviews."
  },
  "12": {
    "id": 12,
    "name": "Summit Suites",
    "address": "1062 D St, Hayward, CA",
    "lat": 37.6548,
    "lng": -122.05505,
    "rent": 1597,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 5.6,
    "distance_miles": 0.2,
    "avg_utilities": 224,
    "true_cost": 1821,
    "utilities_reported": true,
    "avg_rating": 2.5,
    "review_count": 2,
    "reviews": [
      {
        "id": 41,
        "overall_rating": 3,
        "landlord_rating": 1,
        "maintenance_rating": 3,
        "safety_rating": 3,
        "monthly_utilities": 251,
        "text": "Landlord kept part of the deposit for normal wear and tear. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-08-29T17:08:27.576802",
        "verified": true
      },
      {
        "id": 42,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 1,
        "safety_rating": 1,
        "monthly_utilities": 198,
        "text": "Landlord kept part of the deposit for normal wear and tear. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-01-11T17:08:27.576844",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 2 student reviews."
  },
  "1": {
    "id": 1,
    "name": "Hillside Commons",
    "address": "1014 Hayward Blvd, Hayward, CA",
    "lat": 37.66037,
    "lng": -122.08545,
    "rent": 1675,
    "bedrooms": 1,
    "landlord_name": "Eastbay Living",
    "safety_score": 5.0,
    "distance_miles": 1.6,
    "avg_utilities": 147,
    "true_cost": 1822,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 6,
    "reviews": [
      {
        "id": 6,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 206,
        "text": "Management is respectful and gives notice before entering. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-08-12T17:08:27.554284",
        "verified": true
      },
      {
        "id": 5,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 4,
        "monthly_utilities": 101,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-08-12T17:08:27.554251",
        "verified": true
      },
      {
        "id": 1,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 145,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Rent is fair but the walls are thin.",
        "created_at": "2026-08-08T17:08:27.553978",
        "verified": true
      },
      {
        "id": 3,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 4,
        "monthly_utilities": 113,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Rent is fair but the walls are thin.",
        "created_at": "2026-03-31T17:08:27.554173",
        "verified": true
      },
      {
        "id": 4,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 227,
        "text": "Landlord replies within a day and fixed our sink fast. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-03-22T17:08:27.554211",
        "verified": true
      },
      {
        "id": 2,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 91,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-12-08T17:08:27.554116",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 6 student reviews."
  },
  "3": {
    "id": 3,
    "name": "Bayview Flats",
    "address": "2187 Foothill Blvd, Hayward, CA",
    "lat": 37.672,
    "lng": -122.06673,
    "rent": 1620,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 8.3,
    "distance_miles": 1.2,
    "avg_utilities": 203,
    "true_cost": 1823,
    "utilities_reported": true,
    "avg_rating": 4.3,
    "review_count": 3,
    "reviews": [
      {
        "id": 12,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 4,
        "monthly_utilities": 250,
        "text": "Management is respectful and gives notice before entering. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-07-03T17:08:27.569956",
        "verified": true
      },
      {
        "id": 11,
        "overall_rating": 4,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 118,
        "text": "Management is respectful and gives notice before entering. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-12-12T17:08:27.569914",
        "verified": true
      },
      {
        "id": 10,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 242,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2025-11-04T17:08:27.569859",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 3 student reviews."
  },
  "18": {
    "id": 18,
    "name": "Skyline Rooms",
    "address": "286 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.6452,
    "lng": -122.0513,
    "rent": 1690,
    "bedrooms": 1,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 6.0,
    "distance_miles": 0.8,
    "avg_utilities": 215,
    "true_cost": 1905,
    "utilities_reported": true,
    "avg_rating": 4.6,
    "review_count": 5,
    "reviews": [
      {
        "id": 65,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 215,
        "text": "Landlord replies within a day and fixed our sink fast. Rent is fair but the walls are thin.",
        "created_at": "2026-08-26T17:08:27.581476",
        "verified": true
      },
      {
        "id": 64,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 202,
        "text": "Management is respectful and gives notice before entering. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-07-31T17:08:27.581430",
        "verified": true
      },
      {
        "id": 66,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 4,
        "monthly_utilities": 232,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-07-06T17:08:27.581508",
        "verified": true
      },
      {
        "id": 67,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 168,
        "text": "Deposit returned in full, no drama at move-out. Rent is fair but the walls are thin.",
        "created_at": "2025-12-28T17:08:27.581535",
        "verified": true
      },
      {
        "id": 68,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 259,
        "text": "Landlord replies within a day and fixed our sink fast. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2025-11-13T17:08:27.581561",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 5 student reviews."
  },
  "9": {
    "id": 9,
    "name": "Harder Place",
    "address": "622 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.66916,
    "lng": -122.05757,
    "rent": 1770,
    "bedrooms": 1,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.3,
    "distance_miles": 0.9,
    "avg_utilities": 212,
    "true_cost": 1982,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 2,
    "reviews": [
      {
        "id": 32,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 175,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-06-30T17:08:27.574757",
        "verified": true
      },
      {
        "id": 31,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 248,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-03-22T17:08:27.574708",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 2 student reviews."
  },
  "2": {
    "id": 2,
    "name": "Mission Terrace",
    "address": "2899 D St, Hayward, CA",
    "lat": 37.64826,
    "lng": -122.07622,
    "rent": 1909,
    "bedrooms": 1,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 7.5,
    "distance_miles": 1.2,
    "avg_utilities": 160,
    "true_cost": 2069,
    "utilities_reported": true,
    "avg_rating": 2.3,
    "review_count": 3,
    "reviews": [
      {
        "id": 7,
        "overall_rating": 3,
        "landlord_rating": 2,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 104,
        "text": "Landlord kept part of the deposit for normal wear and tear. Rent is fair but the walls are thin.",
        "created_at": "2026-06-30T17:08:27.568853",
        "verified": true
      },
      {
        "id": 8,
        "overall_rating": 2,
        "landlord_rating": 1,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 144,
        "text": "Hard to reach the landlord, took three weeks to get a response. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-04-13T17:08:27.568927",
        "verified": true
      },
      {
        "id": 9,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 233,
        "text": "Package theft happens a lot, and the entry door lock is broken. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-10-27T17:08:27.568971",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 3 student reviews."
  },
  "13": {
    "id": 13,
    "name": "Eden Row",
    "address": "2383 B St, Hayward, CA",
    "lat": 37.66778,
    "lng": -122.0519,
    "rent": 2025,
    "bedrooms": 2,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 6.8,
    "distance_miles": 0.8,
    "avg_utilities": 178,
    "true_cost": 2203,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 6,
    "reviews": [
      {
        "id": 46,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 4,
        "monthly_utilities": 196,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-07-06T17:08:27.577527",
        "verified": true
      },
      {
        "id": 44,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 160,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Rent is fair but the walls are thin.",
        "created_at": "2026-05-12T17:08:27.577466",
        "verified": true
      },
      {
        "id": 47,
        "overall_rating": 5,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 189,
        "text": "Deposit returned in full, no drama at move-out. Rent is fair but the walls are thin.",
        "created_at": "2025-12-18T17:08:27.577555",
        "verified": true
      },
      {
        "id": 43,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 130,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-12-09T17:08:27.577417",
        "verified": true
      },
      {
        "id": 45,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 228,
        "text": "Landlord replies within a day and fixed our sink fast. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2025-09-21T17:08:27.577499",
        "verified": true
      },
      {
        "id": 48,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 5,
        "monthly_utilities": 166,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-08-26T17:08:27.577582",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 6 student reviews."
  },
  "14": {
    "id": 14,
    "name": "Tennyson Gardens",
    "address": "2099 B St, Hayward, CA",
    "lat": 37.65582,
    "lng": -122.04997,
    "rent": 2112,
    "bedrooms": 2,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.7,
    "distance_miles": 0.4,
    "avg_utilities": 182,
    "true_cost": 2294,
    "utilities_reported": true,
    "avg_rating": 2.2,
    "review_count": 4,
    "reviews": [
      {
        "id": 51,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 3,
        "safety_rating": 2,
        "monthly_utilities": 176,
        "text": "Hard to reach the landlord, took three weeks to get a response. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-05-11T17:08:27.578375",
        "verified": true
      },
      {
        "id": 50,
        "overall_rating": 1,
        "landlord_rating": 1,
        "maintenance_rating": 3,
        "safety_rating": 2,
        "monthly_utilities": 208,
        "text": "Landlord kept part of the deposit for normal wear and tear. Rent is fair but the walls are thin.",
        "created_at": "2025-11-22T17:08:27.578346",
        "verified": true
      },
      {
        "id": 49,
        "overall_rating": 3,
        "landlord_rating": 2,
        "maintenance_rating": 3,
        "safety_rating": 2,
        "monthly_utilities": 249,
        "text": "Mold in the bathroom that was never properly fixed. Street parking only and it fills up after 6 PM.",
        "created_at": "2025-10-14T17:08:27.578301",
        "verified": true
      },
      {
        "id": 52,
        "overall_rating": 3,
        "landlord_rating": 2,
        "maintenance_rating": 1,
        "safety_rating": 3,
        "monthly_utilities": 94,
        "text": "Mold in the bathroom that was never properly fixed. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2025-09-01T17:08:27.578404",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 4 student reviews."
  },
  "16": {
    "id": 16,
    "name": "Jackson Square Apts",
    "address": "532 Jackson St, Hayward, CA",
    "lat": 37.65437,
    "lng": -122.06964,
    "rent": 2250,
    "bedrooms": 2,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 7.7,
    "distance_miles": 0.7,
    "avg_utilities": 198,
    "true_cost": 2448,
    "utilities_reported": true,
    "avg_rating": 4.7,
    "review_count": 3,
    "reviews": [
      {
        "id": 57,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 208,
        "text": "Deposit returned in full, no drama at move-out. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-05-19T17:08:27.579879",
        "verified": true
      },
      {
        "id": 58,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 144,
        "text": "Management is respectful and gives notice before entering. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-04-02T17:08:27.579913",
        "verified": true
      },
      {
        "id": 56,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 241,
        "text": "Management is respectful and gives notice before entering. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-02-11T17:08:27.579821",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 3 student reviews."
  },
  "7": {
    "id": 7,
    "name": "Downtown Lofts",
    "address": "2093 Hayward Blvd, Hayward, CA",
    "lat": 37.66295,
    "lng": -122.05017,
    "rent": 2338,
    "bedrooms": 2,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 6.0,
    "distance_miles": 0.6,
    "avg_utilities": 181,
    "true_cost": 2519,
    "utilities_reported": true,
    "avg_rating": 4.3,
    "review_count": 6,
    "reviews": [
      {
        "id": 23,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 150,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Rent is fair but the walls are thin.",
        "created_at": "2026-08-23T17:08:27.573014",
        "verified": true
      },
      {
        "id": 25,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 170,
        "text": "Landlord replies within a day and fixed our sink fast. Rent is fair but the walls are thin.",
        "created_at": "2026-05-22T17:08:27.573116",
        "verified": true
      },
      {
        "id": 27,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 246,
        "text": "Deposit returned in full, no drama at move-out. Rent is fair but the walls are thin.",
        "created_at": "2026-05-19T17:08:27.573174",
        "verified": true
      },
      {
        "id": 26,
        "overall_rating": 4,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 123,
        "text": "Management is respectful and gives notice before entering. Rent is fair but the walls are thin.",
        "created_at": "2026-01-30T17:08:27.573146",
        "verified": true
      },
      {
        "id": 24,
        "overall_rating": 4,
        "landlord_rating": 4,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 156,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2025-12-04T17:08:27.573073",
        "verified": true
      },
      {
        "id": 22,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 239,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2025-09-10T17:08:27.572970",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 6 student reviews."
  },
  "4": {
    "id": 4,
    "name": "Carlos Bee Cottage",
    "address": "2272 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.63848,
    "lng": -122.04857,
    "rent": 2398,
    "bedrooms": 2,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 6.1,
    "distance_miles": 1.3,
    "avg_utilities": 190,
    "true_cost": 2588,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 4,
    "reviews": [
      {
        "id": 14,
        "overall_rating": 3,
        "landlord_rating": 2,
        "maintenance_rating": 2,
        "safety_rating": 3,
        "monthly_utilities": 144,
        "text": "Landlord kept part of the deposit for normal wear and tear. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-07-18T17:08:27.570785",
        "verified": true
      },
      {
        "id": 13,
        "overall_rating": 1,
        "landlord_rating": 2,
        "maintenance_rating": 1,
        "safety_rating": 1,
        "monthly_utilities": 214,
        "text": "Mold in the bathroom that was never properly fixed. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-04-17T17:08:27.570735",
        "verified": true
      },
      {
        "id": 16,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 1,
        "safety_rating": 1,
        "monthly_utilities": 251,
        "text": "Mold in the bathroom that was never properly fixed. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-04-01T17:08:27.570847",
        "verified": true
      },
      {
        "id": 15,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 3,
        "safety_rating": 1,
        "monthly_utilities": 153,
        "text": "Landlord kept part of the deposit for normal wear and tear. Rent is fair but the walls are thin.",
        "created_at": "2026-03-01T17:08:27.570817",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 4 student reviews."
  },
  "15": {
    "id": 15,
    "name": "Palisade Place",
    "address": "227 B St, Hayward, CA",
    "lat": 37.64169,
    "lng": -122.08327,
    "rent": 2470,
    "bedrooms": 3,
    "landlord_name": "J. Ramirez (private owner)",
    "safety_score": 8.7,
    "distance_miles": 1.8,
    "avg_utilities": 194,
    "true_cost": 2664,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 3,
    "reviews": [
      {
        "id": 55,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 3,
        "safety_rating": 4,
        "monthly_utilities": 259,
        "text": "Maintenance is slow, took a week to fix the fridge. Mold in the bathroom that was never properly fixed.",
        "created_at": "2026-07-31T17:08:27.579154",
        "verified": true
      },
      {
        "id": 53,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 4,
        "safety_rating": 3,
        "monthly_utilities": 184,
        "text": "Heating is weak in winter, so the PG&E bill spikes in Dec-Feb. Mold in the bathroom that was never properly fixed.",
        "created_at": "2026-07-19T17:08:27.579077",
        "verified": true
      },
      {
        "id": 54,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 140,
        "text": "Rent is fair but the walls are thin. Landlord kept part of the deposit for normal wear and tear.",
        "created_at": "2026-06-30T17:08:27.579123",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance is hit or miss; some safety concerns reported. Based on 3 student reviews."
  },
  "8": {
    "id": 8,
    "name": "Garden Studio",
    "address": "650 Harder Rd, Hayward, CA",
    "lat": 37.66165,
    "lng": -122.05897,
    "rent": 2503,
    "bedrooms": 3,
    "landlord_name": "Greenleaf Property Mgmt",
    "safety_score": 8.9,
    "distance_miles": 0.4,
    "avg_utilities": 168,
    "true_cost": 2671,
    "utilities_reported": true,
    "avg_rating": 5.0,
    "review_count": 3,
    "reviews": [
      {
        "id": 29,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 175,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-08-26T17:08:27.573985",
        "verified": true
      },
      {
        "id": 30,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 4,
        "safety_rating": 4,
        "monthly_utilities": 109,
        "text": "Quiet building, great for studying. Walkable to the shuttle. Rent is fair but the walls are thin.",
        "created_at": "2026-07-01T17:08:27.574020",
        "verified": true
      },
      {
        "id": 28,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 219,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-05-05T17:08:27.573931",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 3 student reviews."
  },
  "17": {
    "id": 17,
    "name": "Redwood Duplex",
    "address": "2376 Carlos Bee Blvd, Hayward, CA",
    "lat": 37.64692,
    "lng": -122.04268,
    "rent": 2591,
    "bedrooms": 3,
    "landlord_name": "M. Chen (private owner)",
    "safety_score": 9.2,
    "distance_miles": 1.0,
    "avg_utilities": 156,
    "true_cost": 2747,
    "utilities_reported": true,
    "avg_rating": 2.0,
    "review_count": 5,
    "reviews": [
      {
        "id": 62,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 1,
        "safety_rating": 2,
        "monthly_utilities": 139,
        "text": "Landlord kept part of the deposit for normal wear and tear. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-07-22T17:08:27.580708",
        "verified": true
      },
      {
        "id": 60,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 2,
        "safety_rating": 3,
        "monthly_utilities": 231,
        "text": "Package theft happens a lot, and the entry door lock is broken. Street parking only and it fills up after 6 PM.",
        "created_at": "2026-05-31T17:08:27.580645",
        "verified": true
      },
      {
        "id": 63,
        "overall_rating": 2,
        "landlord_rating": 1,
        "maintenance_rating": 2,
        "safety_rating": 2,
        "monthly_utilities": 148,
        "text": "Package theft happens a lot, and the entry door lock is broken. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2026-05-03T17:08:27.580735",
        "verified": true
      },
      {
        "id": 59,
        "overall_rating": 2,
        "landlord_rating": 3,
        "maintenance_rating": 3,
        "safety_rating": 3,
        "monthly_utilities": 94,
        "text": "Mold in the bathroom that was never properly fixed. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-01-14T17:08:27.580592",
        "verified": true
      },
      {
        "id": 61,
        "overall_rating": 2,
        "landlord_rating": 2,
        "maintenance_rating": 3,
        "safety_rating": 2,
        "monthly_utilities": 168,
        "text": "Package theft happens a lot, and the entry door lock is broken. Heating is weak in winter, so the PG&E bill spikes in Dec-Feb.",
        "created_at": "2025-09-05T17:08:27.580679",
        "verified": true
      }
    ],
    "ai_summary": "Landlord often rated poorly; maintenance complaints are common; some safety concerns reported. Based on 5 student reviews."
  },
  "11": {
    "id": 11,
    "name": "Foothill House",
    "address": "2846 B St, Hayward, CA",
    "lat": 37.655,
    "lng": -122.04637,
    "rent": 2818,
    "bedrooms": 3,
    "landlord_name": "Bay Rentals Co.",
    "safety_score": 6.7,
    "distance_miles": 0.6,
    "avg_utilities": 220,
    "true_cost": 3038,
    "utilities_reported": true,
    "avg_rating": 4.5,
    "review_count": 4,
    "reviews": [
      {
        "id": 39,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 200,
        "text": "Deposit returned in full, no drama at move-out. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-02-26T17:08:27.576189",
        "verified": true
      },
      {
        "id": 40,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 258,
        "text": "Landlord replies within a day and fixed our sink fast. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2026-01-26T17:08:27.576216",
        "verified": true
      },
      {
        "id": 38,
        "overall_rating": 5,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 247,
        "text": "Deposit returned in full, no drama at move-out. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2025-12-12T17:08:27.576159",
        "verified": true
      },
      {
        "id": 37,
        "overall_rating": 4,
        "landlord_rating": 5,
        "maintenance_rating": 5,
        "safety_rating": 5,
        "monthly_utilities": 173,
        "text": "Well-lit parking and a locked front gate, I feel safe walking home at night. Maintenance is slow, took a week to fix the fridge.",
        "created_at": "2025-11-06T17:08:27.576113",
        "verified": true
      }
    ],
    "ai_summary": "Landlord rated well; maintenance is reliable; residents feel safe. Based on 4 student reviews."
  }
};
